// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperacaoCarga.Data;

namespace OperacaoCarga.Migrations
{
    [DbContext(typeof(OperacaoCargaContext))]
    [Migration("20210319031250_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OperacaoCarga.Models.Conteiner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaConteiner")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NumeroConteiner")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("StatusConteiner")
                        .HasColumnType("int");

                    b.Property<int>("TipoConteiner")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Conteineres");
                });

            modelBuilder.Entity("OperacaoCarga.Models.Movimentacao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConteinerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoMovimentacao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ConteinerID");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("OperacaoCarga.Models.Movimentacao", b =>
                {
                    b.HasOne("OperacaoCarga.Models.Conteiner", "Conteiner")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ConteinerID");

                    b.Navigation("Conteiner");
                });

            modelBuilder.Entity("OperacaoCarga.Models.Conteiner", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
